# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: workflow test

on:
  workflow_dispatch:
  push:

jobs:
  actions-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      packages: write

    steps:
      - name: Get Docker Info
        run: |
          kubectl config view
          kubectl config get-contexts
          docker info
          minikube start --addons ingress --wait "all"
          minikube status
          kubectl config view
          kubectl config get-contexts
          docker info
          eval $(minikube -p minikube docker-env)
          docker info
# refs/tags/v1.1.4
      - name: Get Tags
        run: |
          myjson='{"name": "wubolin"}'
          value=$(echo $myjson | jq '.name')
          echo "value: $value"
          tag=${{ github.event.ref }}
          if ! [[ $tag =~ "refs/tags" ]]; then
            echo "error: no version tag"
            exit 1
          fi
          
          THIS_TAG=${tag##*/}
          echo "THIS_TAG=${THIS_TAG}" >> "$GITHUB_ENV"
          echo "${THIS_TAG}"
          if [ -z "${THIS_TAG}" ]; then
            echo "error: invalid tags"
            exit 1
          fi 

      - name: Checkout repository
        uses: actions/checkout@v4     

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.THIS_TAG}}
          name: Release ${{env.THIS_TAG}}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            test.tar.gz
